"""
Phase 14: ZIP Download endpoint
GET /projects/{build_id}/download  - Download project as ZIP
"""

import io
import json
import zipfile
from datetime import datetime
from pathlib import Path
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from api_platform.database import get_project, get_project_files, get_build_progress

router = APIRouter(prefix="/projects", tags=["downloads"])


SETUP_INSTRUCTIONS = """# Project Setup Instructions

## Prerequisites
- Python 3.10+
- Node.js 18+ (for frontend)
- pip

## Quick Start

### Backend
```bash
cd backend
pip install -r requirements.txt
uvicorn main:app --reload
```

### Frontend (if included)
```bash
cd frontend
npm install
npm run dev
```

### API Docs
Once running, visit: http://localhost:8000/docs

## Notes
- Backend runs on port 8000 by default
- Frontend runs on port 5173 (Vite) by default
- Generated by AI App Builder v2.1.0
"""


@router.get("/{build_id}/download")
async def download_project_zip(build_id: str):
    """Download a completed project as a ZIP file."""

    # Verify project exists and is done
    project = get_project(build_id)
    if not project:
        raise HTTPException(status_code=404, detail=f"Project {build_id} not found")

    if project["status"] not in ("done", "failed"):
        raise HTTPException(
            status_code=400,
            detail=f"Project is still {project['status']}. Wait for build to complete."
        )

    output_path = project.get("output_path")
    if not output_path:
        raise HTTPException(status_code=404, detail="No output directory found for this project")

    output_dir = Path(output_path)
    if not output_dir.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Project output directory not found at {output_path}"
        )

    # Build ZIP in memory
    zip_buffer = io.BytesIO()
    app_name = project.get("app_name") or build_id
    root_folder = f"{app_name}/"

    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        # Add all generated files
        file_count = 0
        for file_path in output_dir.rglob("*"):
            if file_path.is_file():
                arcname = root_folder + str(file_path.relative_to(output_dir))
                zf.write(file_path, arcname)
                file_count += 1

        # Add metadata.json
        files_db = get_project_files(build_id)
        progress = get_build_progress(build_id)

        metadata = {
            "build_id": build_id,
            "app_name": project.get("app_name"),
            "app_type": project.get("app_type"),
            "complexity": project.get("complexity"),
            "prompt": project.get("prompt"),
            "status": project.get("status"),
            "review_score": project.get("review_score"),
            "debug_score": project.get("debug_score"),
            "created_at": project.get("created_at"),
            "completed_at": project.get("completed_at"),
            "duration_seconds": project.get("duration_seconds"),
            "file_count": file_count,
            "files": [f["file_path"] for f in files_db],
            "build_steps": [
                {
                    "step": p["step"],
                    "name": p["step_name"],
                    "status": p["status"],
                    "timestamp": p["timestamp"],
                }
                for p in progress
            ],
            "generated_by": "AI App Builder v2.1.0",
            "downloaded_at": datetime.utcnow().isoformat(),
        }
        zf.writestr(root_folder + "metadata.json", json.dumps(metadata, indent=2))

        # Add setup instructions
        zf.writestr(root_folder + "SETUP.md", SETUP_INSTRUCTIONS)

    zip_buffer.seek(0)
    zip_size = zip_buffer.getbuffer().nbytes

    safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in app_name)
    filename = f"{safe_name}_{build_id[:8]}.zip"

    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "Content-Length": str(zip_size),
            "X-Build-ID": build_id,
            "X-File-Count": str(file_count),
        },
    )
