"""
agents/architect.py — Designs folder/file structure for a project.
"""
import logging
import json
from pathlib import Path
from agents.base_agent import BaseAgent
from tools.file_writer import create_folder, create_file

logger = logging.getLogger(__name__)

PROMPT_FILE = Path(__file__).parent.parent / "prompts" / "architect.txt"

# Folders that should NOT get __init__.py
NON_PYTHON_FOLDERS = {
    "frontend", "src", "components", "pages", "services", "assets",
    "public", "styles", "css", "js", "images", "static", "dist",
    "node_modules", "database", "docs", "migrations",
}


class Architect(BaseAgent):
    def __init__(self):
        system_prompt = PROMPT_FILE.read_text(encoding="utf-8")
        super().__init__("Architect", system_prompt)

    def run(self, intent: dict, steps: list) -> dict:
        """
        Design and physically create the project folder/file structure.
        """
        logger.info(f"🏗️  Designing architecture for: {intent.get('app_name')}")

        prompt = f"""
Design the complete folder and file structure for this project:

APP SPEC:
{json.dumps(intent, indent=2)}

BUILD PLAN:
{json.dumps(steps, indent=2)}

Return the architecture JSON object.
"""
        architecture = self.think_json(prompt)
        self._scaffold(architecture)

        logger.info(f"✅ Architecture designed: {len(architecture.get('files', []))} files planned")
        return architecture

    def _scaffold(self, architecture: dict):
        """Create all folders, placeholder files, and __init__.py for Python packages."""
        root = architecture.get("root_folder", "project")

        # Create folders
        for folder in architecture.get("folders", []):
            create_folder(f"{root}/{folder}")

        # Create empty placeholder files
        for file_info in architecture.get("files", []):
            path = file_info.get("path", "")
            description = file_info.get("description", "")
            placeholder = f"# {description}\n# This file will be generated by the code generation agents.\n"
            create_file(f"{root}/{path}", placeholder)

        # Add __init__.py to every Python subfolder that doesn't have one
        self._add_init_files(root, architecture)

        logger.info(f"📁 Scaffolded project at: generated_projects/{root}/")

    def _add_init_files(self, root: str, architecture: dict):
        """
        Ensure every folder that contains Python files has an __init__.py.
        This makes them proper Python packages so imports like
        `from models.weather import X` work correctly.
        """
        import config
        from pathlib import Path

        project_root = Path(config.OUTPUT_DIR) / root

        # Collect all folders that contain .py files
        python_folders = set()
        for file_info in architecture.get("files", []):
            path = file_info.get("path", "")
            file_type = file_info.get("type", "")
            if file_type == "python" or path.endswith(".py"):
                folder = str(Path(path).parent)
                if folder != ".":
                    python_folders.add(folder)

        # Also scan architecture folders for any that look like Python packages
        for folder in architecture.get("folders", []):
            # If it's under backend/ and not a frontend folder
            parts = folder.lower().replace("\\", "/").split("/")
            is_frontend = any(p in NON_PYTHON_FOLDERS for p in parts)
            if not is_frontend and "backend" in parts or "tests" in parts:
                python_folders.add(folder)

        # Create __init__.py in each identified Python folder
        for folder in python_folders:
            init_path = f"{root}/{folder}/__init__.py"
            full_init = project_root.parent / init_path  # relative to OUTPUT_DIR
            
            # Only create if it doesn't exist yet
            full_check = Path(config.OUTPUT_DIR) / init_path
            if not full_check.exists():
                create_file(init_path, '"""Auto-generated package init."""\n')
                logger.info(f"  📦 Added __init__.py: {folder}/")


# ── Smoke test ────────────────────────────────────────────
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    import json
    from agents.intent_analyzer import IntentAnalyzer
    from agents.planner import Planner

    user_prompt = "Build a weather dashboard that shows temperature, humidity and a 5-day forecast"

    intent = IntentAnalyzer().run(user_prompt)
    steps  = Planner().run(intent)
    arch   = Architect().run(intent, steps)

    print("\n=== Architecture ===")
    print(f"Root folder: {arch.get('root_folder')}")
    print(f"\nFolders ({len(arch.get('folders', []))}):")
    for f in arch.get("folders", []):
        print(f"  📁 {f}")
    print(f"\nFiles ({len(arch.get('files', []))}):")
    for f in arch.get("files", []):
        print(f"  📄 {f['path']} — {f['description']}")
