"""
agents/architect.py — Phase 20 (Build Isolation + Forbidden File Guard)
========================================================================
Changes vs Phase 19:

1. FORBIDDEN_FILES_POST_PROCESS — even if the LLM generates a forbidden
   file in the architecture JSON, we strip it BEFORE scaffolding so it
   never lands on disk and never ends up in the ZIP.

2. run() now accepts build_id (optional, defaults to "").
   When provided, the root_folder becomes: "{app_name}_{build_id[:8]}"
   This gives every build a unique output directory, preventing rebuild
   contamination where cancelled builds leave stale files that merge into
   the next build's output.

3. architecture["root_folder"] is updated in-place so all downstream agents
   (BackendDeveloper, FrontendGenerator, Tester, Documenter) also write to
   the build-scoped directory.

4. _add_init_files() unchanged — still adds __init__.py to Python packages.
"""
import logging
import json
from pathlib import Path
from agents.base_agent import BaseAgent
from tools.file_writer import create_folder, create_file

logger = logging.getLogger(__name__)

PROMPT_FILE = Path(__file__).parent.parent / "prompts" / "architect.txt"

# Folders that should NOT get __init__.py
NON_PYTHON_FOLDERS = {
    "frontend", "src", "components", "pages", "services", "assets",
    "public", "styles", "css", "js", "images", "static", "dist",
    "node_modules", "database", "docs", "migrations",
}

# Files the LLM must NEVER generate — stripped from arch JSON before scaffold
# Matches both exact filename and path endings
FORBIDDEN_FILES: frozenset[str] = frozenset({
    "setup.py",
    "manage.py",
    "wsgi.py",
    "asgi.py",
    "Makefile",
    "celery.py",
    "migrate.py",
    "seed.py",
    "gunicorn.conf.py",
})


def _is_forbidden(file_path: str) -> bool:
    """Return True if the file path ends with a forbidden filename."""
    name = Path(file_path).name
    return name in FORBIDDEN_FILES


class Architect(BaseAgent):
    def __init__(self):
        system_prompt = PROMPT_FILE.read_text(encoding="utf-8")
        super().__init__("Architect", system_prompt)

    def run(self, intent: dict, steps: list, build_id: str = "") -> dict:
        """
        Design and physically create the project folder/file structure.

        build_id: when provided, appended to root_folder for isolation.
          e.g. app_name="weather_dashboard", build_id="a1b2c3d4"
               → root_folder="weather_dashboard_a1b2c3d4"
        """
        logger.info(f"🏗️  Designing architecture for: {intent.get('app_name')}")

        prompt = f"""
Design the complete folder and file structure for this project:

APP SPEC:
{json.dumps(intent, indent=2)}

BUILD PLAN:
{json.dumps(steps, indent=2)}

Return the architecture JSON object.
"""
        architecture = self.think_json(prompt)

        # ── Phase 20: Build isolation — unique output dir per build ───────────
        base_root = architecture.get("root_folder", intent.get("app_name", "project"))
        if build_id and build_id not in ("undefined", "null"):
            # Sanitise: keep only alphanumeric + underscore
            safe_suffix = "".join(c for c in build_id[:8] if c.isalnum())
            isolated_root = f"{base_root}_{safe_suffix}"
        else:
            isolated_root = base_root

        architecture["root_folder"] = isolated_root

        # ── Phase 20: Strip forbidden files BEFORE scaffold ───────────────────
        original_count = len(architecture.get("files", []))
        architecture["files"] = [
            f for f in architecture.get("files", [])
            if not _is_forbidden(f.get("path", ""))
        ]
        removed = original_count - len(architecture.get("files", []))
        if removed:
            logger.warning(
                f"⚠️  Stripped {removed} forbidden file(s) from architecture "
                f"(setup.py, manage.py, etc.) before scaffolding."
            )

        self._scaffold(architecture)

        logger.info(
            f"✅ Architecture designed: {len(architecture.get('files', []))} files planned "
            f"in '{isolated_root}'"
        )
        return architecture

    def _scaffold(self, architecture: dict):
        """Create all folders, placeholder files, and __init__.py for Python packages."""
        root = architecture.get("root_folder", "project")

        for folder in architecture.get("folders", []):
            create_folder(f"{root}/{folder}")

        for file_info in architecture.get("files", []):
            path        = file_info.get("path", "")
            description = file_info.get("description", "")
            # Double-check: skip forbidden even if somehow still in list
            if _is_forbidden(path):
                logger.warning(f"⚠️  Skipping forbidden file during scaffold: {path}")
                continue
            placeholder = f"# {description}\n# This file will be generated by the code generation agents.\n"
            create_file(f"{root}/{path}", placeholder)

        self._add_init_files(root, architecture)

        logger.info(f"📁 Scaffolded project at: generated_projects/{root}/")

    def _add_init_files(self, root: str, architecture: dict):
        """
        Ensure every folder that contains Python files has an __init__.py.
        """
        import config
        from pathlib import Path

        project_root = Path(config.OUTPUT_DIR) / root

        python_folders = set()
        for file_info in architecture.get("files", []):
            path      = file_info.get("path", "")
            file_type = file_info.get("type", "")
            if file_type == "python" or path.endswith(".py"):
                folder = str(Path(path).parent)
                if folder != ".":
                    python_folders.add(folder)

        for folder in architecture.get("folders", []):
            parts = folder.lower().replace("\\", "/").split("/")
            is_frontend = any(p in NON_PYTHON_FOLDERS for p in parts)
            if not is_frontend and "backend" in parts or "tests" in parts:
                python_folders.add(folder)

        for folder in python_folders:
            init_path  = f"{root}/{folder}/__init__.py"
            full_check = Path(config.OUTPUT_DIR) / init_path
            if not full_check.exists():
                create_file(init_path, '"""Auto-generated package init."""\n')
                logger.info(f"  📦 Added __init__.py: {folder}/")


# ── Smoke test ────────────────────────────────────────────
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    from agents.intent_analyzer import IntentAnalyzer
    from agents.planner import Planner

    user_prompt = "Build a weather dashboard"
    intent = IntentAnalyzer().run(user_prompt)
    steps  = Planner().run(intent)
    arch   = Architect().run(intent, steps, build_id="testbuild1")

    print(f"\nRoot folder: {arch.get('root_folder')}")
    print(f"Files ({len(arch.get('files', []))}):")
    for f in arch.get("files", []):
        print(f"  📄 {f['path']}")
