"""
tools/file_writer.py — File system tools for AI agents.
Agents use these to physically create project files on disk.
"""
import json
import logging
import os
from pathlib import Path

import config

logger = logging.getLogger(__name__)


def _resolve(relative_path: str) -> Path:
    """Always write inside OUTPUT_DIR to keep things safe."""
    base = Path(config.OUTPUT_DIR)
    full = (base / relative_path).resolve()
    # Safety: prevent path traversal outside output dir
    if not str(full).startswith(str(base.resolve())):
        raise ValueError(f"Path traversal detected: {relative_path}")
    return full


def create_folder(folder_path: str) -> str:
    """Create a folder (and any missing parents)."""
    path = _resolve(folder_path)
    path.mkdir(parents=True, exist_ok=True)
    logger.info(f"📁 Created folder: {path}")
    return str(path)


def create_file(file_path: str, content: str = "") -> str:
    """Create a file with optional content. Creates parent folders too."""
    path = _resolve(file_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    logger.info(f"📄 Created file: {path} ({len(content)} chars)")
    return str(path)


def write_json(file_path: str, data: dict | list) -> str:
    """Write a Python dict/list as formatted JSON."""
    content = json.dumps(data, indent=2, ensure_ascii=False)
    return create_file(file_path, content)


def read_file(file_path: str) -> str:
    """Read and return file contents."""
    path = _resolve(file_path)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")
    return path.read_text(encoding="utf-8")


def list_files(folder_path: str = "") -> list[str]:
    """List all files recursively inside a folder."""
    path = _resolve(folder_path)
    if not path.exists():
        return []
    return [
        str(f.relative_to(_resolve("")))
        for f in path.rglob("*")
        if f.is_file()
    ]


def delete_file(file_path: str) -> str:
    """Delete a file."""
    path = _resolve(file_path)
    if path.exists():
        path.unlink()
        logger.info(f"🗑️  Deleted: {path}")
        return f"Deleted: {path}"
    return f"File not found: {path}"


# ── Smoke test ────────────────────────────────────────────
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    print("Testing file_writer tools...\n")

    create_folder("test_project/src")
    create_file("test_project/src/main.py", "print('Hello from AI!')\n")
    create_file("test_project/README.md", "# Test Project\nGenerated by AI App Builder.\n")
    write_json("test_project/config.json", {"name": "test", "version": "0.1.0"})

    print("\nFiles created:")
    for f in list_files("test_project"):
        print(f"  {f}")

    print("\nReading main.py:")
    print(read_file("test_project/src/main.py"))

    delete_file("test_project/config.json")
    print("config.json deleted.")
    print("\n✅ file_writer tests passed!")
